config/routes.rb
Findfriends::Application.routes.draw do
  resources :users
  root :to => 'users#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name

  has_many :friendships
  has_many :friends, through: :friendships

  geocoded_by :full_address

  after_validation :geocode 

  def friends_nearby
    near = []
    self.friends.each do |friend|
      if self.distance_from(friend) < 20
        near << friend
      end
    end
    near
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.create
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findfriends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.collection_select :friend_ids, User.find(:all), :id, :name, multiple: true  %>
  <%= f.submit "Salvar" %>
<% end %>

app/views/users/index.html.erb
<h1>Todos os usuários</h1>

<%= link_to "New user", new_user_path %>
<% if @users.count > 0 %>
  <table>
    <caption>Usuários do sistema</caption>
    <thead>
      <tr>
        <th>Name</th>
        <th>Full Address</th>
        <th>Friends</th>
        <th>Nearby</th>
      </tr>
    </thead>

    <tfoot>
      <tr colspan="4">
        <td>Total de usuários: <%= @users.count %></td>
      </tr>
    </tfoot>

    <tbody>
      <% @users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.full_address %></td>
          <td><%= u.friends.map {|f| f.name}.join(", ") %></td>
          <td><%= u.friends_nearby.map {|f| f.name}.join(", ") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/new.html.erb
<h1>Novo usuário</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.collection_select :friend_ids, User.find(:all), :id, :name, multiple: true  %>
  <%= f.submit "Salvar" %>
<% end %> 